//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleApp.MyDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public string VIN { get; set; }
        public Nullable<int> passport_series_number { get; set; }
        public Nullable<System.DateTime> start_working { get; set; }
        public Nullable<System.DateTime> end_working { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
